import type { Exam } from '../../../contracts/src/exam';

export interface ICSProductOptions {
    appName?: string;
    domain?: string;
}

const DEFAULT_ICS_PRODUCT: Required<ICSProductOptions> = {
    appName: 'njupt-search',
    domain: 'njupt.hicancan.top'
};

const formatICSDate = (isoString?: string): string | null => {
    if (!isoString) return null;
    const withoutTz = isoString.replace(/[+-]\d{2}:\d{2}$|Z$/, '');
    const cleaned = withoutTz.replace(/[-:]/g, '').split('.')[0];
    return cleaned ?? null;
};

const generateUID = (examId: string, domain: string): string => {
    const safeId = encodeURIComponent(examId).replace(/%/g, '_');
    return `exam-${safeId}@${domain}`;
};

const escapeICSValue = (str: string): string => {
    return str
        .replace(/\\/g, '\\\\')
        .replace(/,/g, '\\,')
        .replace(/;/g, '\\;')
        .replace(/\r\n/g, '\\n')
        .replace(/\r/g, '\\n')
        .replace(/\n/g, '\\n');
};

const foldLine = (line: string): string => {
    const encoder = new TextEncoder();
    const bytes = encoder.encode(line);

    if (bytes.length <= 75) return line;

    const result: string[] = [];
    let currentLine = '';
    let currentBytes = 0;
    const maxBytes = 75;
    const continuationMaxBytes = 74;

    for (const char of line) {
        const charBytes = encoder.encode(char).length;
        const limit = result.length === 0 ? maxBytes : continuationMaxBytes;

        if (currentBytes + charBytes > limit) {
            result.push(currentLine);
            currentLine = char;
            currentBytes = charBytes;
        } else {
            currentLine += char;
            currentBytes += charBytes;
        }
    }

    if (currentLine) {
        result.push(currentLine);
    }

    return result.join('\r\n ');
};

export const generateICSContent = (
    exams: Exam[],
    className: string,
    reminders: number[],
    product: ICSProductOptions = {}
): string => {
    if (!exams || exams.length === 0) {
        throw new Error('无法生成日历：未提供有效的考试数据');
    }
    const { appName, domain } = { ...DEFAULT_ICS_PRODUCT, ...product };
    const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//' + domain + '//' + appName + '//CN',
        'X-WR-CALNAME:南邮考试-' + className,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'BEGIN:VTIMEZONE',
        'TZID:Asia/Shanghai',
        'X-LIC-LOCATION:Asia/Shanghai',
        'BEGIN:STANDARD',
        'TZOFFSETFROM:+0800',
        'TZOFFSETTO:+0800',
        'TZNAME:CST',
        'DTSTART:19700101T000000',
        'END:STANDARD',
        'END:VTIMEZONE'
    ];

    exams.forEach((exam) => {
        if (!exam.start_timestamp || !exam.end_timestamp) return;

        const start = formatICSDate(exam.start_timestamp);
        const end = formatICSDate(exam.end_timestamp);
        if (!start || !end) {
            throw new Error(`Invalid exam time for ${exam.id}`);
        }

        const descText = [
            `课程代码: ${exam.course_code || '-'}`,
            `教师: ${exam.teacher || '未知'}`,
            `班级: ${exam.class_name}`,
            `人数: ${exam.count}`,
            exam.notes ? `备注: ${exam.notes}` : '',
            '',
            `Generated by njupt.${domain}`
        ].filter(Boolean).join('\n');

        const location = `${exam.campus ? `[${exam.campus}] ` : ''}${exam.location}`;
        const summary = exam.course_name;

        lines.push('BEGIN:VEVENT');
        lines.push(`UID:${generateUID(exam.id, domain)}`);
        lines.push(`DTSTAMP:${now}`);
        lines.push(`DTSTART;TZID=Asia/Shanghai:${start}`);
        lines.push(`DTEND;TZID=Asia/Shanghai:${end}`);
        lines.push(`SUMMARY:${escapeICSValue('考试: ' + summary)}`);
        lines.push(`LOCATION:${escapeICSValue(location)}`);
        lines.push(`DESCRIPTION:${escapeICSValue(descText)}`);
        lines.push('STATUS:CONFIRMED');

        reminders.forEach(min => {
            lines.push('BEGIN:VALARM');
            lines.push('ACTION:DISPLAY');
            lines.push('DESCRIPTION:Exam Reminder');
            lines.push(`TRIGGER:-PT${min}M`);
            lines.push('END:VALARM');
        });

        lines.push('END:VEVENT');
    });

    lines.push('END:VCALENDAR');
    return lines.map(foldLine).join('\r\n');
};
